---
title: GurYouDeal Landing Page
author: Francesco Caroli
email: francesco@guryoudeal.com
description: Landing page for Guryou Deal
baseurl: "/"
url: ''
defaults:
- scope: ''
  values: ''
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
